config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  devise_for :users
  resources :restaurants do
    resources :foods, only: [:index]
  end
  resources :line_foods, only: %i[index create]
  put 'line_foods/replace', to: 'line_foods#replace'
  resources :orders, only: %i[create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :restaurant
  belongs_to :order, optional: true
  has_one :line_food, dependent: :destroy
end

app/models/line_food.rb
class LineFood < ApplicationRecord
  belongs_to :food
  belongs_to :restaurant
  belongs_to :order, optional: true

  validates :count, numericality: { greater_than: 0 }

  scope :active, -> { where(active: true) }
  scope :other_restaurant, ->(picked_restaurant_id) { where.not(restaurant_id: picked_restaurant_id) }

  def total_amount
    food.price * count
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_foods, dependent: :destroy

  validates :total_price, numericality: { greater_than: 0 }

  def save_with_update_line_foods!(line_foods)
    ActiveRecord::Base.transaction do
      line_foods.each do |line_food|
        line_food.update!(active: false, order: self)
      end
      save!
    end
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :foods, dependent: :destroy
  has_many :line_foods, through: :foods

  validates :name, :fee, :time_required, presence: true
  validates :name, length: { maximum: 30 }
  validates :fee, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @foods = @restaurant.foods
  end

  private

  def food_params
    params.require(:food).permit(:image)
  end
end

app/controllers/line_foods_controller.rb
class LineFoodsController < ApplicationController
  before_action :set_food, only: %i[create replace]

  def index
    line_foods = LineFood.active
    if line_foods.exists?
      render json: {
        line_food_ids: line_foods.map(&:id),
        restaurant: line_foods[0].restaurant,
        count: line_foods.sum(&:count),
        amount: line_foods.sum(&:total_amount)
      }, status: :ok
    else
      render json: {}, status: :no_content
    end
  end

  def create
    if LineFood.active.other_restaurant(@ordered_food.restaurant.id).exists?
      return render json: {
        existing_restaurant: LineFood.other_restaurant(@ordered_food.restaurant.id).first.restaurant.name,
        new_restaurant: Food.find(params[:food_id]).restaurant.name
      }, status: :not_acceptable
    end

    set_line_food(@ordered_food)

    if @line_food.save
      render json: {
        line_food: @line_food
      }, status: :created
    else
      render json: {}, status: :internal_server_error
    end
  end

  def replace
    LineFood.active.other_restaurant(@ordered_food.restaurant.id).each do |line_food|
      line_food.update_attribute(:active, false)
    end

    set_line_food(@ordered_food)

    if @line_food.save
      render json: {
        line_food: @line_food
      }, status: :created
    else
      render json: {}, status: :internal_server_error
    end
  end

  private

  def set_food
    @ordered_food = Food.find(params[:food_id])
  end

  def set_line_food(ordered_food)
    if ordered_food.line_food.present?
      @line_food = ordered_food.line_food
      @line_food.attributes = {
        count: ordered_food.line_food.count + params[:count],
        active: true
      }
    else
      @line_food = ordered_food.build_line_food(
        count: params[:count],
        restaurant: ordered_food.restaurant,
        active: true
      )
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show; end

  def create
    posted_line_foods = LineFood.where(id: params[:line_food_ids])
    order = Order.new(
      total_price: total_price(posted_line_foods)
    )
    if order.save_with_update_line_foods!(posted_line_foods)
      render json: {}, status: :no_content
    else
      render json: {}, status: :internal_server_error
    end
  end

  private

  def total_price(posted_line_foods)
    posted_line_foods.sum(&:total_amount) + posted_line_foods.first.restaurant.fee
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<div class= 'container'>
  <div class= 'row justify-content-between'>
    <% @foods.each do |food| %>
      <div class= 'foods d-flex  center-block'>
        <div class= 'food-content'>
          <div class= 'food-name'>
              <%= food.name %><br>
          </div>
          <div class= 'food-description'>
              <%= food.description %><br>
          </div>
          <div class= 'food-price'>
            <p>$<%= food.price %></p>
          </div>
        </div>
        <div class= 'food-image align-self-center'>
          <% if food.image? %>
            <%= link_to image_tag(food.image.url),'/' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">portfolio</h5>
        <nav class="my-2 my-md-0 mr-md-3">
          <%= link_to 'ちかちゃん', '#', class: "p-2 text-dark" %>
          <%= link_to 'ちかちゃん', '#', class: "p-2 text-dark" %>
          <%= link_to 'ちかちゃん', '#', class: "p-2 text-dark" %>
          <%= link_to 'ちかちゃん', '#', class: "p-2 text-dark" %>
            <% if user_signed_in? %>
              <strong><%= link_to current_user.username, restaurants_path %></strong>
              <%= link_to 'プロフィール変更', edit_user_registration_path, class: "btn btn-outline-primary" %>
              <%= link_to 'ログアウト', destroy_user_session_path, class: "btn btn-outline-primary", method: :delete %>
            <% else %>
              <%= link_to 'サインアップ', new_user_registration_path, class: "btn btn-outline-primary" %>
              <%= link_to 'ログイン', new_user_session_path, class: "btn btn-outline-primary" %>
            <% end %>
        </nav>
      </div>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <footer>
      <nav class="text-white bg-dark nav justify-content-center">
        <p class= 'my-2'>&copy; 2021.5-<%= Time.current.year %>.<%= Time.current.month %> PORTFOLIO</p>
      </nav>
    </footer>
  </body>
</html>

app/views/orders/show.html.erb
注文画面

app/views/restaurants/index.html.erb
<div class= 'container'>
  <div class= 'row'>
    <%= image_tag 'main-cover-image.png',class: 'toppage' %>
  </div>
  <div class= 'row'>
    <% @restaurants.each do |restaurant| %>
      <div class= 'restaurants col-md-4'>
        <div class= 'image'>
          <% if restaurant.image? %>
            <%= link_to image_tag(restaurant.image.url),'/' %>
          <% end %>
        </div>
        <%= restaurant.name %><br>
        <p>配送料：<%= restaurant.fee %>円 <%= restaurant.time_required %>分</p>
      </div>
    <% end %>
  </div>
</div>